# Generated by Django 5.2.13 on 2026-04-17 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLegalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, default='', max_length=120)),
                ('tax_identification_number', models.CharField(blank=True, default='', max_length=120)),
                ('legal_status', models.CharField(blank=True, default='', max_length=120)),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('address_line', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(blank=True, default='', max_length=40)),
                ('representative_full_name', models.CharField(max_length=180)),
                ('representative_role', models.CharField(blank=True, default='', max_length=120)),
                ('representative_id_number', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Company legal profile',
                'verbose_name_plural': 'Company legal profiles',
            },
        ),
    ]
