# Generated by Django 5.2.13 on 2026-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_companylegalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylegalprofile',
            name='admin_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
