# Generated by Django 5.2.13 on 2026-04-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('grace', 'Grace period'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
