# Generated by Django 5.2.13 on 2026-04-20 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_folders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GedShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Lecture'), ('editor', 'Modification')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ged_shares', to='ged.document')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ged_shares', to='ged.documentfolder')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ged_shares_sent', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ged_shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', True), ('folder__isnull', False)), models.Q(('document__isnull', False), ('folder__isnull', True)), _connector='OR'), name='ged_share_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('folder__isnull', False)), fields=('shared_with', 'folder'), name='uniq_ged_share_folder_user'), models.UniqueConstraint(condition=models.Q(('document__isnull', False)), fields=('shared_with', 'document'), name='uniq_ged_share_document_user')],
            },
        ),
    ]
