# Generated by Django 5.2.13 on 2026-04-20 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_department_employeeprofile_department_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PayrollRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('category', models.CharField(choices=[('bonus', 'Prime'), ('benefit', 'Avantage en nature'), ('deduction', 'Retenue')], max_length=20)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'name'),
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='uniq_payroll_rule_category_name')],
            },
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='employees.payroll')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_components', to='employees.payrollrule')),
            ],
            options={
                'ordering': ('rule__category', 'rule__name'),
                'constraints': [models.UniqueConstraint(fields=('payroll', 'rule'), name='uniq_payroll_component_rule')],
            },
        ),
    ]
