# Generated by Django 5.2.13 on 2026-04-20 20:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeeprofile_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='annual_leave_entitlement_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Droit annuel de conges payes (jours calendaires).', max_digits=6),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Responsable hierarchique (valide les demandes de conge).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employee_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
