# Generated by Django 5.2.13 on 2026-04-17 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(blank=True, default='', max_length=3)),
                ('name', models.CharField(max_length=120)),
                ('continent', models.CharField(blank=True, default='', max_length=40)),
                ('capital', models.CharField(blank=True, default='', max_length=120)),
                ('currency_code', models.CharField(blank=True, default='', max_length=10)),
                ('phone_prefix', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geoname_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('region', models.CharField(blank=True, default='', max_length=160)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('population', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='worlddata.country')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['country', 'name'], name='worlddata_c_country_18a1a5_idx'), models.Index(fields=['population'], name='worlddata_c_populat_cd6ba5_idx')],
            },
        ),
    ]
